package ementor;

import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class FormListagemProfessores extends javax.swing.JFrame {

  /**
   * Creates new form FormListagemProfessores
   */
  public FormListagemProfessores() {
    initComponents();
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../images/graduation-hat.png")));
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jScrollPane2 = new javax.swing.JScrollPane();
    tabelaProfessores = new javax.swing.JTable();
    jLabel2 = new javax.swing.JLabel();
    seletor = new javax.swing.JComboBox<>();
    jLabel3 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Listagem de professores");
    setResizable(false);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowOpened(java.awt.event.WindowEvent evt) {
        formWindowOpened(evt);
      }
    });

    tabelaProfessores.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Nome", "Cpf", "Data de nascimento", "Telefone", "Data de admissão", "Salário bruto", "Salário líquido"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, false, false, false, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    tabelaProfessores.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tabelaProfessoresMouseClicked(evt);
      }
    });
    jScrollPane2.setViewportView(tabelaProfessores);

    jLabel2.setText("Lista de professores");

    seletor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Nome", "Cpf", "Data de nascimento", "Telefone", "Data de admissão", "Salário bruto" }));
    seletor.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        seletorActionPerformed(evt);
      }
    });

    jLabel3.setText("Ordenação:");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel2)
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(seletor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(23, 23, 23)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(seletor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 6, Short.MAX_VALUE))
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    Conexao conexao = new Conexao();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

    tabelaProfessores.getTableHeader().setReorderingAllowed(false);
    tabelaProfessores.getTableHeader().setResizingAllowed(false);
    DefaultTableModel tabela;

    ArrayList<Professor> professores = conexao.recuperaProfessores("nome");

    //Busca os professores do banco
    tabela = (DefaultTableModel) tabelaProfessores.getModel();

    //Insere o resultado na tabela
    professores.forEach(professor -> {
      tabela.addRow(new Object[]{professor.nome, professor.cpf, sdf.format(professor.dataNascimento), professor.telefone, sdf.format(professor.getDataAdmissao()), "R$ " + professor.getSalarioBruto(), "R$ " + professor.salarioLiquido()});
    });

  }//GEN-LAST:event_formWindowOpened

  private void tabelaProfessoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProfessoresMouseClicked
    Conexao conexao = new Conexao();

    ArrayList<Professor> professores = conexao.recuperaProfessores("nome");
    professores.get(tabelaProfessores.getSelectedRow()).imprimeDados();
  }//GEN-LAST:event_tabelaProfessoresMouseClicked

  private void seletorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seletorActionPerformed
    Conexao conexao = new Conexao();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

    DefaultTableModel tabela;
    ArrayList<Professor> professores = new ArrayList();

    tabela = (DefaultTableModel) tabelaProfessores.getModel();

    tabela.setRowCount(0);

    int posicaoEscolhida = seletor.getSelectedIndex();

    //Realiza a busca de acordo com o que foi selecionado
    switch (posicaoEscolhida) {
      case 0:
        break;
      case 1:
        professores = conexao.recuperaProfessores("nome");
        break;
      case 2:
        professores = conexao.recuperaProfessores("cpf");
        break;
      case 3:
        professores = conexao.recuperaProfessores("dataNascimento");
        break;
      case 4:
        professores = conexao.recuperaProfessores("telefone");
        break;
      case 5:
        professores = conexao.recuperaProfessores("dataAdmissao");
        break;
      case 6:
        professores = conexao.recuperaProfessores("salarioBruto");
        break;
      default:
        break;
    }

    //Insere os dados retornados na tabela
    professores.forEach(professor -> {
      tabela.addRow(new Object[]{professor.nome, professor.cpf, sdf.format(professor.dataNascimento), professor.telefone, sdf.format(professor.getDataAdmissao()), "R$ " + professor.getSalarioBruto(), "R$ " + professor.salarioLiquido()});
    });
  }//GEN-LAST:event_seletorActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FormListagemProfessores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FormListagemProfessores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FormListagemProfessores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FormListagemProfessores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new FormListagemProfessores().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JComboBox<String> seletor;
  private javax.swing.JTable tabelaProfessores;
  // End of variables declaration//GEN-END:variables
}
