package ementor;

import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class FormListagemAlunos extends javax.swing.JFrame {

  /**
   * Creates new form FormListagemAlunos
   */
  public FormListagemAlunos() {
    initComponents();
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../images/graduation-hat.png")));
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jScrollPane3 = new javax.swing.JScrollPane();
    tabelaAlunos = new javax.swing.JTable();
    jLabel1 = new javax.swing.JLabel();
    seletor = new javax.swing.JComboBox<>();
    jLabel3 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Listagem de usuários");
    setResizable(false);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowOpened(java.awt.event.WindowEvent evt) {
        formWindowOpened(evt);
      }
    });

    tabelaAlunos.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Nome", "Cpf", "Data de nascimento", "Telefone", "Matrícula", "Período"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, false, false, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    tabelaAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tabelaAlunosMouseClicked(evt);
      }
    });
    jScrollPane3.setViewportView(tabelaAlunos);

    jLabel1.setText("Lista de usuários");

    seletor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Nome", "Cpf", "Data de nascimento", "Telefone", "Matrícula", "Período" }));
    seletor.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        seletorActionPerformed(evt);
      }
    });

    jLabel3.setText("Ordenação:");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(seletor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(23, 23, 23)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(seletor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    Conexao conexao = new Conexao();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

    tabelaAlunos.getTableHeader().setReorderingAllowed(false);
    tabelaAlunos.getTableHeader().setResizingAllowed(false);
    DefaultTableModel tabela;

    ArrayList<Aluno> alunos = conexao.recuperaAlunos("nome");

    tabela = (DefaultTableModel) tabelaAlunos.getModel();

    //Insere na tabela o resultado
    alunos.forEach(aluno -> {
      tabela.addRow(new Object[]{aluno.nome, aluno.cpf, sdf.format(aluno.dataNascimento), aluno.telefone, aluno.getMatricula(), aluno.getPeriodo()});
    });

  }//GEN-LAST:event_formWindowOpened

  private void seletorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seletorActionPerformed
    Conexao conexao = new Conexao();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

    DefaultTableModel tabela;
    ArrayList<Aluno> alunos = new ArrayList();

    tabela = (DefaultTableModel) tabelaAlunos.getModel();

    tabela.setRowCount(0);

    int posicaoEscolhida = seletor.getSelectedIndex();

    //Busca os dados do banco de acordo com a opção escolhida
    switch (posicaoEscolhida) {
      case 0:
        break;
      case 1:
        alunos = conexao.recuperaAlunos("nome");
        break;
      case 2:
        alunos = conexao.recuperaAlunos("cpf");
        break;
      case 3:
        alunos = conexao.recuperaAlunos("dataNascimento");
        break;
      case 4:
        alunos = conexao.recuperaAlunos("telefone");
        break;
      case 5:
        alunos = conexao.recuperaAlunos("matricula");
        break;
      case 6:
        alunos = conexao.recuperaAlunos("periodo");
        break;
      default:
        break;
    }

    //Insere na tabela o resultado
    alunos.forEach(aluno -> {
      tabela.addRow(new Object[]{aluno.nome, aluno.cpf, sdf.format(aluno.dataNascimento), aluno.telefone, aluno.getMatricula(), aluno.getPeriodo()});
    });
  }//GEN-LAST:event_seletorActionPerformed

  private void tabelaAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaAlunosMouseClicked
    Conexao conexao = new Conexao();
    //Quando clicar na linha, imprime os dados daquele aluno
    ArrayList<Aluno> alunos = conexao.recuperaAlunos("nome");
    alunos.get(tabelaAlunos.getSelectedRow()).imprimeDados();
  }//GEN-LAST:event_tabelaAlunosMouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FormListagemAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FormListagemAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FormListagemAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FormListagemAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new FormListagemAlunos().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JComboBox<String> seletor;
  private javax.swing.JTable tabelaAlunos;
  // End of variables declaration//GEN-END:variables
}
