package ementor;

import java.awt.Toolkit;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

public class FormAlteracaoAluno extends javax.swing.JFrame {

  /**
   * Creates new form FormCadastroUsuario
   */
  public FormAlteracaoAluno() {
    initComponents();
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../images/graduation-hat.png")));
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    txtTelefone = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    txtPeriodo = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    txtCpf = new javax.swing.JTextField();
    txtMatricula = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    txtNome = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    txtDataNascimento = new javax.swing.JTextField();
    btnAlterar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Alterar dados do aluno");
    setResizable(false);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowOpened(java.awt.event.WindowEvent evt) {
        formWindowOpened(evt);
      }
    });

    jLabel4.setText("Telefone");

    jLabel5.setText("Matrícula");

    jLabel1.setText("Nome");

    jLabel6.setText("Período");

    jLabel2.setText("CPF");

    jLabel3.setText("Data de nascimento");

    btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
    btnAlterar.setText("  Alterar");
    btnAlterar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAlterarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(26, 26, 26)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jLabel4)
              .addComponent(txtDataNascimento)
              .addComponent(jLabel3)
              .addComponent(txtNome)
              .addComponent(txtCpf)
              .addComponent(jLabel2)
              .addComponent(jLabel1)
              .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAlterar))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(txtMatricula)
              .addComponent(txtPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel6)
              .addComponent(jLabel5))))
        .addGap(24, 24, 24))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(49, 49, 49)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(12, 12, 12)
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(12, 12, 12)
            .addComponent(jLabel6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(92, 92, 92)))
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnAlterar))
        .addContainerGap(27, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    //Quando aperta enter, clica no botão alterar
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    getRootPane().setDefaultButton(btnAlterar);
    Conexao conexao = new Conexao();
    //JOptionPane para ler a matrícula do aluno a ser buscado
    String matricula = JOptionPane.showInputDialog(null, "Digite a matrícula do aluno", "Busca do aluno", JOptionPane.QUESTION_MESSAGE);
    //Caso usuário não digite nada
    if (matricula == null || matricula.isEmpty()) {
      JOptionPane.showMessageDialog(null, "A matrícula não foi encontrada", "Erro!", JOptionPane.ERROR_MESSAGE);
      //Fecha o formulário
      this.dispose();
    } else {
      //Busca o aluno
      Aluno aluno = conexao.recuperaAlunoMatricula(Long.parseLong(matricula));
      //Caso não encontre o aluno
      if (aluno == null) {
        JOptionPane.showMessageDialog(null, "A matrícula não foi encontrada", "Erro!", JOptionPane.ERROR_MESSAGE);
        this.dispose();
      } else {
        //Caso encontre, preenche o formulário
        txtCpf.setEditable(false);
        txtMatricula.setEditable(false);

        txtCpf.setText(String.valueOf(aluno.cpf));
        txtDataNascimento.setText(sdf.format(aluno.dataNascimento));
        txtMatricula.setText(String.valueOf(aluno.getMatricula()));
        txtNome.setText(aluno.nome);
        txtPeriodo.setText(String.valueOf(aluno.getPeriodo()));
        txtTelefone.setText(aluno.telefone);
      }
    }
  }//GEN-LAST:event_formWindowOpened

  private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
    Conexao conexao = new Conexao();
    //Caso algum dos campos não esteja preenchido, mostra uma mensagem de erro
    if (txtNome.getText().isEmpty() || txtDataNascimento.getText().isEmpty() || txtCpf.getText().isEmpty() || txtTelefone.getText().isEmpty() || txtMatricula.getText().isEmpty() || txtPeriodo.getText().isEmpty()) {
      JOptionPane.showMessageDialog(null, "Preencha todos os campos!", "Erro", ERROR_MESSAGE);
    } else {
      //Caso todos os dados estejam certos, realiza a alteração no banco e fecha o formulário
      SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
      try {
        conexao.alteraAluno(txtNome.getText(), sdf.parse(txtDataNascimento.getText()), Long.parseLong(txtCpf.getText()), txtTelefone.getText(), Long.parseLong(txtMatricula.getText()), Integer.parseInt(txtPeriodo.getText()));
        this.dispose();
      } catch (ParseException ex) {
        JOptionPane.showMessageDialog(null, "Formato de data inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
        txtDataNascimento.setText("");
      }
    }
  }//GEN-LAST:event_btnAlterarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FormAlteracaoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FormAlteracaoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FormAlteracaoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FormAlteracaoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new FormAlteracaoAluno().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAlterar;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JTextField txtCpf;
  private javax.swing.JTextField txtDataNascimento;
  private javax.swing.JTextField txtMatricula;
  private javax.swing.JTextField txtNome;
  private javax.swing.JTextField txtPeriodo;
  private javax.swing.JTextField txtTelefone;
  // End of variables declaration//GEN-END:variables
}
